spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_demo_store
    username: demo_user
    password: demo_pass
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration

# Spring Security - in-memory authentication
  security:
    user:
      name: admin
      password: admin123

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect