spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_demo_store
    username: demo_user
    password: demo_pass
    driver-class-name: org.postgresql.Driver

# Spring Security - in-memory authentication
spring:
  security:
    user:
      name: admin
      password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect