spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/books_store
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

app:
  security:
    admin-password: admin123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update